# Generated by Django 4.0.5 on 2022-06-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('articleTitle', models.CharField(max_length=50, verbose_name='文章标题')),
                ('articleContent', models.CharField(max_length=1000, verbose_name='文章内容')),
                ('articleTime', models.CharField(default='', max_length=50, verbose_name='文章发布时间')),
                ('articleImagePath', models.CharField(max_length=100, verbose_name='图片地址')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='新闻ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
                ('postTime', models.CharField(max_length=30, verbose_name='新闻发布时间')),
                ('imgList', models.CharField(max_length=100, verbose_name='新闻图片')),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('typeId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='新闻类型ID')),
                ('typeName', models.CharField(max_length=10, verbose_name='新闻类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(max_length=30, verbose_name='新闻唯一ID')),
                ('images', models.CharField(max_length=500, verbose_name='新闻详情图片列表')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
                ('content', models.CharField(max_length=10000, verbose_name='新闻内容')),
                ('ptime', models.CharField(max_length=30, verbose_name='新闻发布时间')),
                ('cover', models.CharField(max_length=100, verbose_name='新闻封面图片')),
                ('newsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCtl.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='newsTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCtl.newstype'),
        ),
    ]
