# Generated by Django 4.0.5 on 2022-06-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('newsId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='新闻ID')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
                ('postTime', models.CharField(max_length=30, verbose_name='新闻发布时间')),
                ('imgList', models.TextField(blank=True, verbose_name='新闻图片')),
                ('digest', models.TextField(verbose_name='新闻摘要')),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('typeId', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='新闻类型ID')),
                ('typeName', models.CharField(max_length=10, verbose_name='新闻类型名称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='昵称')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('sex', models.CharField(blank=True, max_length=10, verbose_name='性别')),
                ('sign', models.TextField(blank=True, verbose_name='个性签名')),
                ('avatar', models.CharField(blank=True, max_length=100, verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('docid', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='新闻唯一ID')),
                ('images', models.TextField(verbose_name='新闻详情图片列表')),
                ('title', models.CharField(max_length=100, verbose_name='新闻标题')),
                ('source', models.CharField(max_length=20, verbose_name='新闻来源')),
                ('content', models.TextField(verbose_name='新闻内容')),
                ('ptime', models.CharField(max_length=30, verbose_name='新闻发布时间')),
                ('cover', models.CharField(max_length=100, verbose_name='新闻封面图片')),
                ('newsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCtl.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='newsTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCtl.newstype'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('articleTitle', models.CharField(max_length=50, verbose_name='文章标题')),
                ('articleContent', models.CharField(max_length=1000, verbose_name='文章内容')),
                ('articleTime', models.CharField(default='', max_length=50, verbose_name='文章发布时间')),
                ('articleImagePath', models.CharField(max_length=100, verbose_name='图片地址')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBCtl.user')),
            ],
        ),
    ]
