# Generated by Django 4.0.5 on 2022-06-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBCtl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='userId',
            new_name='user',
        ),
    ]
