# Generated by Django 4.0.5 on 2022-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCtl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imgList',
            field=models.TextField(blank=True, verbose_name='新闻图片'),
        ),
    ]
