# Generated by Django 4.0.5 on 2022-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBCtl', '0002_rename_userid_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
