# Generated by Django 4.0.5 on 2022-06-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCtl', '0003_remove_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleContent',
            field=models.TextField(verbose_name='文章内容'),
        ),
    ]
